import type { Metadata } from "next";
import { StoreProvider } from "./storeProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Toaster position="bottom-center" />
        <StoreProvider> 
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
